name: release

on:
  push:
    tags:
      - "v*"
    branches: [ master ]

jobs:
  g8:
    runs-on: ubuntu-latest

    steps:
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      - name: Install CS native
        run: |
          curl -fLo cs https://git.io/coursier-cli-linux
          chmod +x cs
          sudo mv cs /usr/local/bin

      - name: Install giter8
        run: |
          cs install giter8
          sudo mv /home/runner/.local/share/coursier/bin/g8 /usr/local/bin
          cd /usr/local/bin
          chmod +x g8

      - name: Cache ~/.cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-coursier-${{ hashFiles('project/Libs.scala') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Cache ~/.sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Giter8 Compile
        run: |
          g8 tmtsoftware/esw-backend-template.g8 --name=appserver
          cd appserver
          sbt clean test

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
